---
- name: Create Nodes and Bucket
  hosts: tags_Name_soleil_ansible*
  gather_facts: true
  become: true
  vars_files:
    - "vars.yaml"
  roles: 
    # - create_bucket
    # - node_create
    - send_logs